### ISSUE TITLE
Repo description is incorrect: Firefox is also supported

### ISSUE THREAD

**Issue by xuhdev** [jitsi/jidesha#11]

**Comment by damencho** [comment]
It is said in the description "Extension for Firefox and Chrome for Desktop Sharing in Jitsi Meet.".

**Comment by xuhdev** [comment]
I meant the repo description " A Chrome extension for Desktop Sharing in Jitsi Meet "

**Comment by damencho** [comment]
I got it, thanks. Fixed.
