### ISSUE TITLE
Jidesha installing

### ISSUE THREAD

**Issue by jy2008** [jitsi/jidesha#15]
I am hosting rocket.chat on my own server but not Jitsi, and rocket.chat is using Jitsi for the video chat. 
So in my case, if I am using Jitsi's server for the video chat through rocket.chat, do i still need to install Jidesha in order for my users to use screen share ?  I do get the error message: failed to install desktop extension.

If so, is there a tutorial or instruction in terms of how to get Jidesha up running? there is nothing in Github.

**Comment by damencho** [comment]
https://github.com/jitsi/jidesha/tree/master/chrome
