### ISSUE TITLE
Chrome - full desktop - infinite children

### ISSUE THREAD

**Issue by techdad** [jitsi/jidesha#21]
Hi,

I'm not sure how else to describe this other than the subject.

Both Jitsi Meet and the extension work just fine in Chrome when sharing either an Application Window or Chrome Tab. However, when testing sharing the full desktop, it's sort of like mirrors facing one another... the sharing is shared, which is shared, which is shared.. 

See attached screenshot:
<img width="951" alt="afrinic_jitsi_meet_and_downloads" src="https://cloud.githubusercontent.com/assets/991914/22365809/f0d8365a-e492-11e6-8968-8eef045a2825.png">

This is Chrome 55 on macOS 10.11 (El Capitan). This is with only the host connected. My assumption is that with another person in the conference and them given focus, this may not happen. Still to be tested, it's a new set up.

Also, not checked on FF yet.

**Comment by damencho** [comment]
Please use the mailing list for questions and problems before opening new issues.

You will see the exact same with FF. And the same if you put a mirror in front of another mirror :) This is not a problem, test it with real partisipants to see the behaviour.

**Comment by quoclv** [comment]
This "infinite children" only happens on Chrome running on Mac OS (i.e. if you share entire screen using Chrome on Mac OS you will see the issue). It doesn't happens when you share the screen using Chrome on Windows OS.

**Comment by damencho** [comment]
@quoclv I just tested it on windows I see the same behavior. If you share your screen and show your conference it is the same everywhere, you see the shared conference, which shows your shared conference, which shows your shared conference, which shows your shared conference ... I don't see how this can be different on different OS if your screen sharing works, showing your desktop.

**Comment by quoclv** [comment]
@damencho interesting. I just tried it again with the site https://meet.jit.si and I can still see it is working fine when sharing from Chrome (version 65) on Windows OS (Windows 10).

From Chrome on Windows OS, when you click on the share button, you will see as following:
<img width="640" alt="screen shot 2018-04-07 at 9 54 11 am" src="https://user-images.githubusercontent.com/7554333/38450553-08b05ba0-3a4a-11e8-81f0-1dae897895e5.png">

You can see that the image under the section "Your Entire Screen" seems still have the "infinite" issue. However, after you click on the share button, the screen sharing seen from Chrome on the Mac OS side will see it is shared correctly as following:

<img width="640" alt="screen shot 2018-04-07 at 9 54 33 am" src="https://user-images.githubusercontent.com/7554333/38450563-39916f66-3a4a-11e8-97ce-5ab11a9f5787.png">

**Comment by damencho** [comment]
You are testing it wrong. You are seeing the other participant, you need to click on your local video and you will see the infinity.
Look at my second comment, the thing you see is the normal situation when sharing the full screen.

**Comment by quoclv** [comment]
@damencho Looking at the local video will see the infinity is definitely expected. The issue here is if you share our screen from Chrome on Mac OS to Chrome on Windows OS, the Chrome on Windows OS will also the "infinity" issue.

However, the issue seems to be with the Virtual Machine (I am running the Windows OS as a VM with VMWare Fusion). I tested again with two different laptops and didn't see the issue.

Thank you for your follow up.
