### ISSUE TITLE
One Jidesha plugin (per browser) to rule them all

### ISSUE THREAD

**Issue by luk43** [jitsi/jidesha#23]
Hi
I Just wanted to ask if there's a demand to pull in one jidesha plugin in the
firefox addon store and chrome addon web store, where you can manually point to
your own jitsi-meet installation instead of building your own plugin to do this.

E.g.: Add a configurable input field exposed in the browser plugin settings.

This way, you need only one build for everyone.

**Comment by damencho** [comment]
Please use the users/dev mailinglist for questions and problems before opening issues.

Starting firefox 52 addon or whitelisting is not needed anymore. I'm not sure that plugin for * domain will work. When uploading the chrome extension you need to specify site, which domain you need to verify. Not sure what will happen without that part configured, will it work for all different domains.
