### ISSUE TITLE
Plugin not compatible with firefox e10s

### ISSUE THREAD

**Issue by mbtuckersimm** [jitsi/jidesha#24]
This addon is not compatible with the new electrolysis multiprocess framework for firefox. Here's a screenshot from the add-ons menu. Sorry I have no further information about this.

![notcompatiblee10s](https://cloud.githubusercontent.com/assets/7231911/23593488/7a814506-01c4-11e7-8a3c-7a0a98a7c960.png)

**Comment by bgrozev** [comment]
Thank you for the report @mbtuckersimm. I suspect that the extension is actually compatible, but hasn't properly declared it. Note that the extension will not be required any more starting with firefox 52, so I this may not be a high priority to solve right now.

**Comment by mbtuckersimm** [comment]
Thanks for getting back to me so quickly!

**Comment by bgrozev** [comment]
To clarify: does this prevent you from using screen sharing?

**Comment by mbtuckersimm** [comment]
Screen sharing in hipchat with multiprocess enabled in firefox did seem to
work ok in my limited test, as you suspected. I guess we can close the file
on that one!

**Comment by bgrozev** [comment]
Cool, thank you for confirming.
