### ISSUE TITLE
Chrome extension does not work on personal server

### ISSUE THREAD

**Issue by marcheschi** [jitsi/jidesha#33]
Hi
I installed the jitsi server on an ubuntu and it works fine , screeen sharing is working on firefox with the same site.

I tried to compile the calendar  crx extension with my site and it does not work for me.

Instead the original extension jitsi meetings works fine with the https://meet.jit.si/ site.

so I guess it is an error in configuration of my server.

when I add the generated ID to the server :

// The ID of the jidesha extension for Chrome.
    desktopSharingChromeExtId: omikhipjhdfmdnemgfifenclnmaphebc,
    // Whether desktop sharing should be disabled on Chrome.
    desktopSharingChromeDisabled: false,
    // The media sources to use when using screen sharing with the Chrome
    // extension.
    desktopSharingChromeSources: ['screen', 'window', 'tab'],
    // Required version of Chrome extension
    desktopSharingChromeMinExtVersion: '0.1',

and I restart the jicofo service, I got a blank screen
What I'm missing ?

Thank you
Paolo

**Comment by saghul** [comment]
Looks like you are missing single quotes around the extension ID.

**Comment by marcheschi** [comment]
Yes 
Now it works !!!
Thank you very much
Maybe you can add an example in the readme file

Paolo
