### ISSUE TITLE
Failure to download a custom extension using jidesha from Chrome Store

### ISSUE THREAD

**Issue by SheriefAlaa** [jitsi/jidesha#35]
Hello,

I've used the instructions to create a private extension, added it to the chrome store, configured jitsi-meet to use the extension's ID but it keeps failing to download the extension from the Chrome Store and all it does is spit a "Permissions denied" popup.

Extension's page: `https://chrome.google.com/webstore/detail/ojddellhmdkbkejiklmlaemehnbkfigb/publish-accepted?hl=en-US&gl=US`

Error generated inside the console:
`app.bundle.min.js:2 [react/features/base/tracks/functions.js] <>:  Failed to create local tracks ["desktop"] r {name: "gum.chrome_extension_installation_error", message: "Failed to install the extension from https://chrom…/webstore/detail/ojddellhmdkbkejiklmlaemehnbkfigb", stack: "Error↵    at new r (https://app.boardhub.io/libs/l…er.onInstallResponse (extensions::webstore:72:22)"}`

Any help would be much appreciated.

Thanks.

**Comment by damencho** [comment]
I see this error:
Failed to install the extension from https://chrome.google.com/webstore/detail/ojddellhmdkbkejiklmlaemehnbkfigb Inline installs can only be initiated for Chrome Web Store items that have one or more verified sites.

Did you verify the site? There is a step when uploading the extension that you need to point a verified site and there are few steps to verify the domain with html file or dns record.

**Comment by SheriefAlaa** [comment]
Thank you. It works.
