### ISSUE TITLE
Inline Installation API deprecation

### ISSUE THREAD

**Issue by Ark74** [jitsi/jidesha#41]
If I understood correctly the current inline installation process that Jidesha uses will be deprecated by September 2018.

https://blog.chromium.org/2018/06/improving-extension-transparency-for.html

Would this be a blocking issue for Jidesha?

**Comment by damencho** [comment]
We are aware of this. You can also follow: https://bugs.chromium.org/p/chromium/issues/detail?id=326740#c68
The inline installation will no longer work after the chrome changes, but the extension will still be able to be installed and used. If there are changes needed in jitsi-meet we will make sure everything works as expected.
We expect that after the implementing the changes in the bug mentioned above, there will no longer be needed an extension.

**Comment by Ark74** [comment]
Great to know! Thanks for the info.
Please close this issue at your convenience.

**Comment by thefallman** [comment]
Would you consider to get rid of Chrome screen share extension at all?
The `chrome.desktopCapture.*` API is getting more and more mature, so waht's the reason supporting 2 APIs which provide the same functionality?

**Comment by saghul** [comment]
This is already the case. If you use Chrome Canary you should be getting screen sharing without any extension.

**Comment by roeycohen** [comment]
that's great news!
since chrome 70 was already released, why clicking share desktop button at meet.jit.si still requires the extension?

**Comment by saghul** [comment]
I believe this was fixed in 72, which is current stable, can you give that a try?

**Comment by roeycohen** [comment]
i'll try and let you know.

how about the docs? i'm using lib-jitsi-meet directly...

**Comment by saghul** [comment]
Sorry, I lied :-P 71 does not yet have `getDisplayMedia` in the right place. Even if you enable experimental web platform features, the extension is needed because we look for `navigator.mediaDevices.getDisplayMedia` which works only on >= 72.

Let me try a quick fix.

**Comment by roeycohen** [comment]
i've tried on canary 73 and it works really great :)
now i just need a workaround for the next month... i'm getting the following error:
![2019-01-02 12_45_14-devtools - localhost_lms42_](https://user-images.githubusercontent.com/2613845/50588787-583b4380-0e8c-11e9-8389-6108423c723b.png)

**Comment by saghul** [comment]
@roeycohen Give this patch a try: https://github.com/jitsi/lib-jitsi-meet/pull/851 with it, M71 with xperimental platform features enabled does not require the extension.

**Comment by roeycohen** [comment]
i've made the checked you've requested: the patch worked for me when activated enable-experimental-web-platform-features.

can you please direct me on how to solve the problem with the extension installation?

**Comment by damencho** [comment]
@roeycohen When experimental-web-platform-features is disabled the extension installation should be working fine. Have you created an extension for your deployment, upload it to google webstore, verify the site and configure extension id in config.js?

**Comment by roeycohen** [comment]
@damencho the patch @saghul supplied did work with the flag, but my users aren't that sophisticated :)
in order to continue working with the extension, i needed to add the following code:
```
let tracks = await JitsiMeetJS.createLocalTracks({
	devices: ['desktop'],
	desktopSharingExtensionExternalInstallation: {
		interval: 500,
		checkAgain: () => this.installWindow && !this.installWindow.closed,
		listener: (status, url) =>
		{
			switch (status)
			{
				case 'waitingForExtension':
				{
					if (!this.installWindow || this.installWindow.closed)
						this.installWindow = window.open(url, 'extension_store_window', 'resizable,scrollbars=yes,status=1');
					else
						this.installWindow.focus();
					break;
				}
				case 'extensionFound':
					this.installWindow.close();
					break;
				default:

				// Unknown status
			}
		}
	}
});
```

**Comment by damencho** [comment]
Yep, this is how it is supposed to work, jitsi-meet code seems similar I think:
https://github.com/jitsi/jitsi-meet/blob/b7b43e8d9c582910aa043a522fbe1b19500c2b44/conference.js#L1492

**Comment by roeycohen** [comment]
yes, i've created this code based on the jitsi-meet project code.
I wonder if updating the lib-jitsi-meet docs worth the effort when next month chrome 72 is released...

**Comment by pedro-nonfree** [comment]
What I have to change to recover the previous funcionality (before inline installation) that clicking sharing desktop redirected user to the chrome web store?

**Comment by damencho** [comment]
@pedro-nonfree update to latest
https://github.com/jitsi/lib-jitsi-meet/commit/75a556e3950dfc396d7aa8306b42de67f372e1cf

**Comment by saghul** [comment]
@damencho Do you think we can close this now?

**Comment by damencho** [comment]
Yep. The current inline installation code had been removed and this or next week we will update stable.

**Comment by damencho** [comment]
approximately, cannot give you an exact estimation. We need to deploy it on meet.jit.si first and then (after 2-3 days) we will push it to stable.

**Comment by damencho** [comment]
It is available now in stable.

**Comment by pedro-nonfree** [comment]
@damencho thank you so much,  I tried it and works as expected!
