### ISSUE TITLE
Screen sharing show unlimited loopings

### ISSUE THREAD

**Issue by havid0707** [jitsi/jidesha#44]
Sometimes, screen sharing shows unlimited nesting/loopings when sharing entire screen. any idea to fix this. thanks a lot

**Comment by saghul** [comment]
Are you looking at the same screen you are sharing? In that case this is not possible to fix.

**Comment by saghul** [comment]
Correct. Your screen replaces your local video.

**Comment by havid0707** [comment]
The following two cases also cause ```unlimited loopings```
1. When share type as "Application" and I choose the browser which run Jitsi Meet
2. When share type as "Chrome Tab" and I choose the tab which run Jitsi Meet

Is it possible to solve this?

**Comment by saghul** [comment]
It's not possible to solve this. It's the same as attaching pointing a camera to its own preview. There is nothing we can do about it.

**Comment by havid0707** [comment]
@saghul  Thanks for your info.
 Can we filter out the current one（Application / Tab）? The purpose is to prevent users from choosing them.

**Comment by saghul** [comment]
No, that UI is presented by the browser itself, we have no control over it.

**Comment by havid0707** [comment]
@saghul  Thanks.
one more case:
Video conference with only two people, For example, A and B, A share entire screen, B use normal camera.

We already know that if A look at his local video will produce ```unlimited loopings``` . 
The problem is the B side. if B look at remote video(from A),Will also produce ```unlimited loopings```。

B can only view himself?

you can test https://meet.jit.si to reproduce this case.

**Comment by saghul** [comment]
@havid0707 I don't know what you are asking me to do here. Why would anyone share their screen and stay on meet?! Screen sharing is intended to show something to someone, foe example an application or a tab, or even the entire screen, but not to be looking at oneself. That's what creates the loop, but that problem is between the keyboard and the chair :-)

**Comment by havid0707** [comment]
I found that the cause of the error was ```remote desktop B machine.```
I am sorry for this case.  thanks for your help.
