### ISSUE TITLE
Creating jitsi meet using Google Calendar 

### ISSUE THREAD

**Issue by minkyul** [jitsi/jidesha#45]
I successfully installed jidesha for desktop sharing and scheduling a jitsi event using google calendar.
Desktop sharing is working fine but sometimes the event in the google calendar does not have the "location" information. It is not very consistent; sometimes the event does have the location, but not always.

Did anyone experience this? Is it a known bug?

-Minkyu

**Comment by damencho** [comment]
Yep, editing those fields is tricky. We've been testing it a lot and haven't noticed any issues, but it will not surprise me for cases where it doesn't work.
We are working on that.

**Comment by jtoy** [comment]
any insights into this? how is it?

**Comment by damencho** [comment]
We are currently working on adding calendar addon with which you can schedule meetings the same way you can use Hangouts for calendar events. 
This addon will deprecate the calendar integration in jidesha that is for google calendar.

**Comment by sumitoberoi1** [comment]
@damencho Is there any update on Google Calendar Addon

**Comment by damencho** [comment]
Nope, sorry.

**Comment by sumitoberoi1** [comment]
@damencho Thanks for the reply.
Is this(https://gsuite.google.com/marketplace/app/jitsi_meet_for_google_calendar/421935948107) based on jidesha?

**Comment by damencho** [comment]
Nope. This is a google addon, which API is still not public.

**Comment by sumitoberoi1** [comment]
Ok! a slightly unrelated question. Did you guys use Google App Script for this?

**Comment by damencho** [comment]
Yes.

**Comment by sumitoberoi1** [comment]
I have been struggling to figure out the complete process for app script. 
Can you provide a big-picture overview of the project?
How your team or you did it? I am struggling on how to add my meeting config in conference dropdown where it shows Hangout/Jitsi-meet?

I appreciate your help on a completely unrelated topic from the ticket

**Comment by sumitoberoi1** [comment]
Ok! So the API to add custom video conferencing is not publically available and you need Google's permission to access it?

**Comment by damencho** [comment]
That is correct.

**Comment by sumitoberoi1** [comment]
Thanks again for the help

**Comment by sumitoberoi1** [comment]
Hey @damencho Is there an online resource to help me apply for the API.
Can you guide me on how you applied for the API?

**Comment by damencho** [comment]
Sorry, I don't know. We got an invitation from Google while working with them on some other subject...

**Comment by bobbercheng** [comment]
@damencho 
Did you open source for calendar addon(https://gsuite.google.com/marketplace/app/jitsi_meet_for_google_calendar/421935948107)? I cannot find it on github.

**Comment by damencho** [comment]
The source code for the addon will be published once the API is public, which is still not public. Sorry.

**Comment by bobbercheng** [comment]
@damencho 
Google Gadgets API is public as https://developers.google.com/gadgets. Do you mean the API for google calendar is still not public?

**Comment by damencho** [comment]
Google Calendar Addons API is not public.

**Comment by hthetiot** [comment]
Hello @damencho,  I have found the way to actually implement the Calendar Addon by reverse engineering Google Calendar source code and existing sparse information on internet.


Note: See Sylaps options
<img width="242" alt="Screen Shot 2019-12-05 at 2 18 27 PM" src="https://user-images.githubusercontent.com/8635/70239297-56989080-176b-11ea-8a9e-8d6de1b0ced0.png">

I understand that officialy the access to this "API" is not Public but it's  actually available in plain sight for who knows how to look for it. And does not seem to require any special privilege to use, install, and deploy the custom Calendar Addon. 

<img width="925" alt="Screen Shot 2019-12-05 at 2 29 45 PM" src="https://user-images.githubusercontent.com/8635/70239514-bdb64500-176b-11ea-881f-5071bf9af698.png">

- https://developers.google.com/calendar/v3/reference/events#conferenceData

Right now I only have an issue due that I'm doing reverse engineering, is with `conferenceData` `entryPoints` that are not returned and a missing `conferenceSolutionType` entry in the response and it is stuck on "Adding Conference Details" despite properly populating and returning `conferenceData` with success and 200 Status.

I think the process to officialy get access to the API is to apply to "G Suite Add-ons (beta)" at the following URL (I will confirm once/If get approved).

- https://gsuite.google.com/campaigns/index__add-ons-beta.html

<img width="655" alt="Screen Shot 2019-12-05 at 2 38 32 PM" src="https://user-images.githubusercontent.com/8635/70240397-7466f500-176d-11ea-915c-fc0e87e4b79c.png">
<img width="563" alt="Screen Shot 2019-12-05 at 2 39 03 PM" src="https://user-images.githubusercontent.com/8635/70240398-7466f500-176d-11ea-9a96-696d331a320b.png">

**Comment by damencho** [comment]
Thanks for the information. I didn't know that, and this can be really useful for those that want to use it.

**Comment by hthetiot** [comment]
I confim that to implement google calendar addon you need to apply to the G Suite Add-ons (beta) program, here https://gsuite.google.com/campaigns/index__add-ons-beta.html

Note: My previous message as been edited to match following requirements "Confidential material: Do not share or discuss until authorized to do so."

**Comment by damencho** [comment]
> Note: My previous message as been edited to match following requirements "Confidential material: Do not share or discuss until authorized to do so."

Thanks for the update. Yep, this is the reason why the add-on is not open-sourced.

**Comment by christefano** [comment]
FYI, the G Suite Add-ons Beta program form now says:

> Thank you for your interest in G Suite Add-ons. As of February 4, 2020, G Suite Add-ons are generally available. You can check out currently available G Suite Add-ons at https://gsuite.google.com/marketplace/category/works-with-gsuite and learn more about building add-ons at https://developers.google.com/gsuite/add-ons/concepts/types#g_suite_add-ons

I’m able to install the Jitsi Meet for Google Calendar add-on here: https://gsuite.google.com/marketplace/app/jitsi_meet_for_google_calendar/421935948107

Unfortunately for me and my self-hosted Jitsi Meet server, as one of the commenters has said:

> Doesn't work with a custom Jitsi server, only meet.jit.si. Fair enough but could be stated more explicitly. Also, does not allow changing / setting the meeting URL, which seems like a pretty fundamental feature.

**Comment by ThisGuyCodes** [comment]
@damencho I'm curious if the closed-source addon only works for meet.jit.si (as opposed to letting you point it at your own instance) due to restrictions imposed by google for gsuite addons?

**Comment by damencho** [comment]
It works only for meet.jit.si. I will be checking this week when I have time the APIs and whether we are allowed to publish the code, if that is so, I will create a repo with it and will ping you here and closing this issue. So stay tuned.

**Comment by damencho** [comment]
It is still not public as said on https://developers.google.com/gsuite/add-ons/concepts/types#g_suite_add-ons
```
These add-ons require a well-developed third-party conferencing solution for the add-on to connect to. Because of this requirement, Calendar conferencing add-ons were kept in an extended beta phase and not documented publicly for some time. Most developers don't have any need to ever develop a conferencing add-on.
```

**Comment by lievenjanssen** [comment]
@MichielDeMey I read it in the same way so I would have interpreted the text as out of beta..

**Comment by damencho** [comment]
I don't see the documents publicly available and I still see the warning on them, 'private do not share' ...

**Comment by lievenjanssen** [comment]
@damencho do you have a contact at Google I can reach out to to discuss this? Currently Google is in a state that you can't request a beta anymore, it says that it's public but there is no public documentation yet which doesn't really make sense.

**Comment by damencho** [comment]
Nope sorry.

**Comment by damencho** [comment]
We did the initial import of the code of the Calendar Addon you can find today in the gsuite store.

Any recommendations, PRs, and updating docs (as there are non in the moment ) and such are more than welcome! Thank you.

https://github.com/jitsi/calendar-addon

**Comment by Yolakalemowa** [comment]
> It works only for meet.jit.si. I will be checking this week when I have time the APIs and whether we are allowed to publish the code, if that is so, I will create a repo with it and will ping you here and closing this issue. So stay tuned.

Hi, is this still the case? or can we now choose a diff. instance to be integrated in calendar other than official jitsi?
