### ISSUE TITLE
should I compile-update regularly the chrome/chromium extension?

### ISSUE THREAD

**Issue by pedro-nonfree** [jitsi/jidesha#47]
I compiled the chrome/chromium long time ago (before it had the thing for the calendar). And I think the screen capture is not working. Should I compile-update again the new extension? In case I should update the extension what is the criteria to update the extension, I see 0 releases, how can I know when is the good moment?

Thank you!

**Comment by damencho** [comment]
Since chrome 72 extension is not needed anymore.

**Comment by pedro-nonfree** [comment]
Yaaaay! Great news. That's true, in debian stable with Chrome/Chromium it is version 72 and share screen works without plugin (I deleted it). And looks like I did not need any config thing.

Closing this!
