### ISSUE TITLE
Update phone #s inserted by Jitsi Meetings Chrome extension

### ISSUE THREAD

**Issue by cvdseverine** [jitsi/jidesha#52]
## Description
I have a very small request to update the text that is automatically inserted by the Jitsi Meetings Chrome extension to reflect the current dial-in numbers.

As we’re located in Canada, having the Canadian number available is useful, however it doesn’t appear in the extension text when creating a calendar invite.

## Current behavior
Dial-in numbers inserted by the Chrome extension are not the most recent

## Expected Behavior
Chrome extension will insert the most recent dial-in numbers

## Possible Solution
Update the numbers

## Steps to reproduce
Create a calendar invite with the Jitsi Meetings Google Chrome extension

# Environment details
Windows 10 Pro 1909
Chrome Version 81.0.4044.129 (Official Build) (64-bit)
Jitsi Meetings extension Version 0.2.8.14

**Comment by damencho** [comment]
Fixed.
