### ISSUE TITLE
Problem share screen in ubuntu

### ISSUE THREAD

**Issue by mirohe** [jitsi/jidesha#7]
Hello,

Mi system is:

Ubuntu 14.04
Graphical Environement is Unity
Firefox 44.0
jidesha 0.1.1

When I share screen with any program, not scale correctly and the other users see it wrong. 
For example, if I share screen with libreoffice calc, the column "A" and part of "B"  is not seen for the rest of users that is connected.
The problem also persists if I change the window size of that program or any other shared program. The scale is not correct.
This problem existed in previous versions of firefox, and this is tested from firefox user to firefox user.

Best regards

**Comment by bgrozev** [comment]
The problem you describe is likely not directly connected with jidesha. It sounds like a client (jitsi-meet?) issue. Please describe your problem (and include instructions to reproduce) to dev@jitsi.org.

**Comment by mirohe** [comment]
Hello bgrozev,

I reproduced this problem with two computer over my desktop, facing each other, with the same software, plugins (jidesha) and SO as I described above.

Best regards
