### ISSUE TITLE
Installed extension but i get the "Failed to install desktop extension" message

### ISSUE THREAD

**Issue by gradinaruvasile** [jitsi/jidesha#8]
Hi,
I cloned the repository, modified the chrome/manifest.json file then packed and installed the extension in Chrome.
After that i modified /etc/jitsi/meet/my.domain-config.js and added the 
`desktopSharingChromeExtId: 'myextensionid',`
line and restarted everything with 
`systemctl restart jicofo && systemctl restart jitsi-videobridge && systemctl restart prosody && systemctl restart nginx`
I started Chrome, connected to my domain, reloaded the page with ctrl+f5 (tried also ctrl-r, ctrl-shift-r).
I tried setting 
`desktopSharing: 'webrtc'`
and
`desktopSharing: 'ext'`
But both give the same results:
When i click on the "Share Desktop" icon, i get the "Failed to install desktop extension" message.
What is the issue?

I tried this on Google Chrome 49.0.2623.87-1 (the "stable" package), on Debian Testing 64 bit.

**Comment by bgrozev** [comment]
This is very unlikely to be a problem with jidesha, but rather the application which uses it (jitsi-meet). Please open an issue there (or better yet write to the dev@jitsi.org mailing list) and include your config.js file and the output from the javascript console.
