### ISSUE TITLE
Some annotations for your plugins

### ISSUE THREAD

**Issue by YugiFanGX** [jitsi/jidesha#9]
Finally, I got your plugin working and I must tell you that I really appreciate your work as part of an open source project. Now, after testing both, the Firefox and the Chrome plugin, I would like to ask you some questions:

1. Why is there no option to define the URL of the Chrome extension file on the Jitsi Meet server? When using Firefox I can set a link to my XPI file, but with Chrome's CRX I can not. Even if the CRX would have been installed instantly after downloading it, it should be possible to inform the user to right click and save it to a certain location of the current PC.

2. In Chrome you are able to share the whole screen, but with the Firefox Addon only Windows can be streamed to the other person. Is this due to the Firefox API or could you also implement a feature to share the whole screen with the Firefox Plugin?

Thank you so much for your work
I'm looking forward to your reply

**Comment by damencho** [comment]
Please use the mailinglist for discussing things and asking questions before creating issues.
1. jidesha for chrome is supposed to be installed in Chrome webstore, and it is automatically downloaded and installed from there depending the id that is set in the config file. Sending CRX file is the way to go doing it by hand and as there is automatic way of downloading stuff there is no implementation currently for downloading and installing by hand by users. Any patches are welcome.
2. That behavior is browser specific and how they implemented desktop sharing.
